# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prod_predict <- function(prices) {
    .Call('stat385tester_prod_predict', PACKAGE = 'stat385tester', prices)
}

