// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prod_predict
Rcpp::NumericVector prod_predict(Rcpp::NumericMatrix prices);
RcppExport SEXP stat385tester_prod_predict(SEXP pricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type prices(pricesSEXP);
    rcpp_result_gen = Rcpp::wrap(prod_predict(prices));
    return rcpp_result_gen;
END_RCPP
}
